version: '3.1'
services:
  stats:
    build: ./stats/stat-server
    image: stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - EWM_SERVER_URL=http://stats-server:9090
      -
  stat-db:
    image: postgres:13.7-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - STAT_POSTGRES_PASSWORD=stats
      - STAT_POSTGRES_USER=ewm
      - STAT_POSTGRES_DB=ewm

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - EWM_POSTGRES_PASSWORD=ewm
      - EWM_POSTGRES_USER=ewm
      - EWM_POSTGRES_DB=ewm


  emw:
    build: ./ewm
    image: ewm
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      - stats
      - ewm-db
