version: '3.1'
services:
  stats:
    build: ./stats/stat-server
    image: stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - EWM_SERVER_URL=http://stats-server:9090
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm

  emw:
    build: ./ewm
    image: ewm
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      - stats
