package ru.practicum.ewm.models.event;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ru.practicum.ewm.enums.State;
import ru.practicum.ewm.models.category.Category;
import ru.practicum.ewm.models.location.Location;
import ru.practicum.ewm.models.user.User;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "Event")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor(staticName = "create")
public class Event {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    String annotation;
    @ManyToOne
    @JoinColumn(name = "category")
    Category category;
    @Column(name = "created_on")
    LocalDateTime createdOn;
    String description;
    @Column(name = "event_date")
    LocalDateTime eventDate;
    @ManyToOne
    @JoinColumn(name = "user")
    User initiator;
    @ManyToOne
    @JoinColumn(name = "location")
    Location location;
    Boolean pain;
    @Column(name = "participant_limit")
    Integer participantLimit;
    @Column(name = "request_moderation")
    Boolean requestModeration;
    @Enumerated(EnumType.STRING)
    State state;
    String title;
    /*
        ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ANNOTATION VARCHAR                                        NOT NULL,
    CATEGORY BIGINT NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR,
    EVENT_DATE TIMESTAMP NOT NULL,
    INITIATOR BIGINT NOT NULL,
    LOCATION BIGINT NOT NULL,
    PAID BOOL NOT NULL,
    PARTICIPANT_LIMIT INT NOT NULL,
    REQUEST_MODERATION BOOL NOT NULL,
    STATE INT NOT NULL,
    TITLE VARCHAR NOT NULL,
    */

}
