DROP TABLE IF EXISTS participant_request, location, users, category;
DROP TABLE IF EXISTS compilation, event CASCADE;

CREATE TABLE IF NOT EXISTS event
(
    ID                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ANNOTATION         VARCHAR                                             NOT NULL,
    CATEGORY           BIGINT,
    CREATED_ON         TIMESTAMP                                           NOT NULL,
    DESCRIPTION        VARCHAR,
    EVENT_DATE         TIMESTAMP                                           NOT NULL,
    INITIATOR          BIGINT                                              NOT NULL,
    LOCATION           BIGINT                                              NOT NULL,
    PAID               BOOL                                                NOT NULL,
    PARTICIPANT_LIMIT  INT                                                 NOT NULL,
    REQUEST_MODERATION BOOL                                                NOT NULL,
    PUBLISHED_DATE     TIMESTAMP,
    STATE              VARCHAR                                             NOT NULL,
    TITLE              VARCHAR                                             NOT NULL
);

CREATE TABLE IF NOT EXISTS participant_request
(
    ID       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    CREATED  TIMESTAMP                                           NOT NULL,
    USER_ID  BIGINT                                              NOT NULL,
    EVENT_ID BIGINT                                              NOT NULL,
    STATUS   VARCHAR                                             NOT NULL
);

CREATE TABLE IF NOT EXISTS location
(

    ID       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    EVENT_ID BIGINT                                              NOT NULL,
    LAT      FLOAT                                               NOT NULL,
    LON      FLOAT                                               NOT NULL

);

CREATE TABLE IF NOT EXISTS users
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(254)                                        NOT NULL UNIQUE,
    NAME  VARCHAR(250)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS category
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    NAME VARCHAR(50)                                         NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilation
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    EVENT  BIGINT,
    PINNED BOOL                                                NOT NULL,
    TITLE  VARCHAR
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    COMPILATION_ID BIGINT REFERENCES compilation (ID),
    EVENT_ID       BIGINT REFERENCES event (ID)
);

CREATE TABLE IF NOT EXISTS comments
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    USER_ID       BIGINT    NOT NULL,
    EVENT_ID      BIGINT    NOT NULL,
    TEXT       VARCHAR(256),
    CREATED    TIMESTAMP NOT NULL,
    CONSTRAINT user_event_id UNIQUE (USER_ID, EVENT_ID)
)